# Generated by Django 4.1.7 on 2023-02-26 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inventario',
            new_name='Inventory',
        ),
    ]
