# Generated by Django 4.1.7 on 2023-02-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventario", "0002_rename_inventario_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="price",
            field=models.IntegerField(),
        ),
    ]
