# Generated by Django 4.1.7 on 2023-02-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Inventario", "0003_alter_inventory_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("stock", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="warehouse",
            fields=[
                (
                    "idWarehouse",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="inventory",
            old_name="price",
            new_name="priceUnit",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="id",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="stock",
        ),
        migrations.AddField(
            model_name="inventory",
            name="code",
            field=models.CharField(
                default=1, max_length=100, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventory",
            name="resume",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventory",
            name="idWarehouse",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Inventario.warehouse",
            ),
            preserve_default=False,
        ),
    ]
